### ISSUE TITLE
Adapt Command Line documentation due to the removal of the XHTML section from the Capella documentation

### ISSUE THREAD

**Issue by sandupostaru** [eclipse/capella-xhtml-docgen#159]
The following Capella issue https://github.com/eclipse/capella/issues/2033 plans to remove the dedicated section to XHTML Command Line Documentation.

That section should be contributed by the XHTML add-on and not be directly present in the Capella product.

**Comment by arnauddieumegard** [comment]
Merged in master 5.0.0.
