### ISSUE TITLE
searchIndex.html is not generated

### ISSUE THREAD

**Issue by emmateo** [eclipse/capella-xhtml-docgen#194]
Hello,

Defining an CapellaOutgoingRelation with only one end-point defined the searchIndex.html is not generated.
For example: Source=LogicalFunction1 Target=[Undefined]

Thanks before-hand,
Enrique

**Comment by arnauddieumegard** [comment]
Hi,

We have fixed something that looks very much like this problem in version 0.12.1 of the Requirements Viewpoint (https://github.com/eclipse/capella-requirements-vp/releases/tag/v0.12.1) are you using this version ?

Regards,
Arnaud

**Comment by arnauddieumegard** [comment]
Closed as assumed to be already fixed. Please ask to be reopened if necessary.
