### ISSUE TITLE
Capella 6.0.0 Mass Views

### ISSUE THREAD

**Issue by thierry112** [eclipse/capella-xhtml-docgen#224]
Hi all,
I just tried to build both mass visualization view and mass editing view in a new project and a migrated from 5.2.0:
No list happens:
![image](https://user-images.githubusercontent.com/107460255/193780663-6759eebf-68a2-4208-9c91-1359582bc2be.png)
Thanks for information

**Comment by arnauddieumegard** [comment]
Hello,

The root of the problem has been found and reported here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=580921
A workaround is documented here: https://forum.mbse-capella.org/t/mass-view-with-capella-6-0-0/5776/2

Regards.
